### PR TITLE
Fix apply format command

### PR DESCRIPTION
**Pull request by XLegland**
related to #137

### CODE REVIEW

**Comment by XLegland** [comment]
@gdevillele I think we need a secret or a bot account so the workflow can push to the repo

**Comment by gdevillele** [comment]
> @gdevillele I think we need a secret or a bot account so the workflow can push to the repo

We could, indeed, but I think we can do without.

With `act` on our machines, we absolutely need a `GITHUB_TOKEN` (see https://github.com/nektos/act#github_token) but in a regular GitHub action, running on Github, the token of the user doing the `/format` command will be provided (from my understanding).

**Review by gdevillele — APPROVED** [review]
LGTM 👍

**Pull request merged**
