### PR TITLE
Port CI pipelines to Dagger Modules

### PR DESCRIPTION
**Pull request by shykes**
This implements a Dagger Module, and moves most of the existing Dagger pipeline logic to that module.

## Benefits

- The building blocks of Cubzh CI pipelines (build, test, lint) are encapsulated into reusable software components called *Dagger Functions*
- Dagger Functions are containerized, so there is no dependency other than Dagger. This makes it easier to run the same pipeline in CI and in dev, without "it works on my machine". Also, no more need to setup go tooling in CI before running.
- Dagger Functions are loaded directly into the Dagger Engine, and extend the Dagger API. So there is no need to develop custom tools, with their own main function, etc. This makes the overall code simpler
- Dagger Functions can be called directly from the Dagger CLI with `dagger call`, or by other functions - cross-language. So later it will be easier to build more and more complex pipelines, without having to wrap shell scripts in shell scripts.

## Status

| Before | After | After (next version of dagger) | Note |
| -- | -- | -- | -- |
| `go run ./ci linter` | `dagger call lint-modules --src=.:modules` | `dagger call lint-module` | Combined `lua-check` and `stylua` for simplicity |
| `go run ./ci formater` | `dagger call lint-modules --src=.:modules` | `dagger call lint-modules` | Combined `lua-check` and `stylua` for simplicity |
| `go run ./ci/format --apply-changes` | `dagger call format-core --src=.:format-core -o .` | `dagger call format-core -o .` | `-o` to re-apply the output directory to the local filesystem |
| `go run ./ci/core_unit_tests` | `dagger call test-core --src=.:test-core` | `dagger call test-core` | |
| `go run ./ci/lua_docs_deploy_prod` | *not converted* | *not converted* ||

### CODE REVIEW

**Comment by shykes** [comment]
@aduermael @gdevillele this is ready for review :)

**Review by aduermael — DISMISSED** [review]
Looks really good to me, thank you so much! 😊

**Comment by aduermael** [comment]
Oh, talked a bit too fast, we'll need statuses to be reported! 😬

**Review by aduermael — APPROVED** [review]
LGTM! (for real this time)

**Pull request merged**
