### PR TITLE
ci: generate (some) github actions pipelines

### PR DESCRIPTION
**Pull request by shykes**
This uses a Dagger pipeline to generate the Github Actions pipelines to run our Dagger pipelines.

To generate, run this command from the root of the repo:

```
dagger call -m .github config -o .github
```

### CODE REVIEW

**Comment by shykes** [comment]
FYI @aduermael @gdevillele  :)

**Comment by shykes** [comment]
@aduermael @gdevillele  I tried to use the same workflow names in the generated config, not sure why the "required checks" config is not matched... Would you mind sharing a screenshot of that setting, so I can understand the problem?

**Comment by gdevillele** [comment]
@shykes this ?

Screenshot 2024-08-15 at 22 41 14

Thanks a lot for the PR!!

**Comment by gdevillele** [comment]
@shykes could it be related to the "source"?

Screenshot 2024-08-15 at 22 42 50

**Comment by shykes** [comment]
@gdevillele I checked on another repo, and I don't understand why it doesn't match... Would you mind giving me admin access to the repo temporarily, so I can take a look? I suspect it takes into account the filename, even though the check names look identical in the UI. So I may have to just delete and re-create the required checks.

**Comment by shykes** [comment]
Ping @gdevillele @aduermael, if you give me (temporary) admin access on the repo I am happy to check on these required checks myself.

**Comment by shykes** [comment]
ready for review @aduermael :)

**Review by aduermael — APPROVED** [review]
Awesome, thank you @shykes! 🙂

**Pull request merged**
