### PR TITLE
CI : disable on “main” branch pushes

### PR DESCRIPTION
**Pull request by gdevillele**

### CODE REVIEW

**Comment by XLegland** [comment]
@gdevillele Shouldn't we trigger the ci only on pushes that are not on the `main` branch? https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs

**Comment by gdevillele** [comment]
> @gdevillele Shouldn't we trigger the ci only on pushes that are not on the `main` branch? https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs

We already trigger the CI on "pushes on pull requests that target `main`".
Don't you think it is enough?

```
pull_request:
     branches:
       - main
```

**Comment by XLegland** [comment]
Alright, that's fine for me

**Review by XLegland — APPROVED** [review]
LGTM

**Comment by gdevillele** [comment]
@XLegland thanks

**Pull request merged**
