### PR TITLE
Remove URL from social network usernames

### PR DESCRIPTION
**Pull request by XLegland**

### CODE REVIEW

**Comment by gdevillele** [comment]
could you explain the issue please? this allows to paste the profile URL ? like 
```
https://github.com/gdevillele
```

**Comment by XLegland** [comment]
@gdevillele The ticket is here: https://linear.app/cubzh/issue/CUB-815/social-network-buttons-above-the-game-menu
The issue was that is wasn't clear whether the user has to enter only the username or the whole link

**Comment by gdevillele** [comment]
I tried it.

- For TikTok, I suppose it was not tested. The URL looks like `https://www.tiktok.com/@cubzh`
- For X/Twitter it works (`https://twitter.com/cubzh_`)
- For GitHub it works (`https://github.com/gdevillele`)

**Comment by gdevillele** [comment]
I fixed the behaviour for TikTiok, but we should have a full URL parsing at some point.

**Review by gdevillele — APPROVED** [review]
LGTM 👍

**Pull request merged**
