### PR TITLE
Core tests: vertexbuffer

### PR DESCRIPTION
**Pull request by XLegland**

### CODE REVIEW

**Comment by XLegland** [comment]
Points to clarify:
- how MemAreas are created? (same for MemAreaWriter)
- What are draw slices

**Comment by ArthurVoxowl** [comment]
`VertexBufferMemAreaWriter` are created on demand when writing vertices, while `VertexBufferMemArea` represents bits of adjacent data inside one buffer. Draw slices represent a slice of data that has changed and needs to be updated rendere-side for the effect to become visible on screen. All of these are used by a shape at runtime.

We will think about functional tests for these, but as far as unit tests go, this is about what can be done!

**Review by M0UTOO — DISMISSED** [review]
LGTM 👍

**Review by M0UTOO — APPROVED** [review]
You can merge :)

**Pull request merged**
